package Testing_extra;

import org.testng.Reporter;
import org.testng.annotations.Test;

public class Demo1 {
	
//Reporter class: This class is used for test methods to log messages 
//	              that will be included in the HTML reports generated by TestNG.
	
    @Test
    public void case1() {
	   Reporter.log("case 2 : Plz go elsewhere....");// Report
	   
    }
    
    @Test
    public void case2() {
	   Reporter.log("case 3 : Plz go elsewhere....",true);// Report
	   
    } 
}
